import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Navbar from "./my-components/navbar";
import Footer from "./my-components/footer";
import CookieConsent from "./my-components/cookie-consent";
import { Providers } from "./my-components/Providers";
import AccountDeletedHandler from "./profile/ProfileAccountDeleteHandler";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "NEWS4U",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased overflow-scroll",
          fontSans.variable
        )}
      >
        <Providers>
          <AccountDeletedHandler />
          <Navbar />
          {children}
          <Footer />
        </Providers>
        <CookieConsent />
        <Toaster />
      </body>
    </html>
  );
}
