import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Navbar from "./my-components/navbar";
import Footer from "./my-components/footer";
import CookieModal from "./my-components/cookie-modal";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased pb-10 overflow-scroll",
                    fontSans.variable
                )}
            >
                <Navbar />
                {children}
                <Footer />
                <CookieModal />
                <Toaster />
            </body>
        </html>
    );
}
